CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'egenc'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'egenc'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
